### ISSUE TITLE
Will this run on Raspberry Pi / Windows 10 IoT Core?

### ISSUE THREAD

**Issue by hansmbakker** [charlesportwoodii/libsodium-uwp#19]
In the readme I saw that you need to include ```Visual C++ Redistributable for Visual Studio 2015``` in your project and I'm not sure that is available for Raspberry.

Will this Nuget package work for Raspberry Pi / Windows 10 IoT Core?

**Comment by charlesportwoodii** [comment]
@wind-rider,

It's not something I've explicitly tried, but I don't see why it wouldn't. It compiles to arm, and if your app can consume a universal c runtime or is a UWP app it should work. 

As an aside though, I'd clone the repo (--recursive) instead of using the nuget package. For some reason the nuget package doesn't always link right in VS2015. `master` is currently = to the latest tag. 

Give it a shot the provide us with an update?
